const contentImages = {
  'Luke Skywalker': './luke.jpg',
  'C-3PO': './C3PO.jpeg',
  'R2-D2': './R2D2.jpeg',
  'Darth Vader': './DV.jpeg',
  'Leia Organa': './Leia.jpeg',
  'Owen Lars': './OwenL.jpeg',
  'Beru Whitesun lars': './BeruL.jpeg',
  'R5-D4': './R5D4.jpeg',
  'Biggs Darklighter': './BiggsD.jpeg',
  'Obi-Wan Kenobi': './Obiwan.jpeg',
  Alderaan: './Alderaan.jpeg',
  'Yavin IV': './Yavin.jpeg',
  Hoth: './Hoth.jpeg',
  Dagobah: './Dagobah.jpeg',
  Bespin: './Bespin.jpeg',
  Endor: './Endor.jpeg',
  Naboo: './Naboo.jpeg',
  Coruscant: './Coruscant.jpeg',
  Kamino: './Kamino.jpeg',
  Geonosis: './Geonosis.jpeg',
  'Sand Crawler': './SandC.jpeg',
  'T-16 skyhopper': './T16.jpeg',
  'X-34 landspeeder': './X34.jpeg',
  'TIE/LN starfighter': './Starfighter.jpeg',
  Snowspeeder: './Snowspeeder.jpeg',
  'TIE bomber': './TIEbomber.jpeg',
  'AT-AT': './ATAT.jpeg',
  'AT-ST': './ATST.jpeg',
  'Storm IV Twin-Pod cloud car': './StormIV.jpeg',
  'Sail barge': './SailBarge.jpeg',
};

module.exports = contentImages;
