const contentImages = {
  "Luke Skywalker": "./images/luke.jpg",
  "C-3PO": "./images/C3PO.jpeg",
  "R2-D2": "./images/R2D2.jpeg",
  "Darth Vader": "./images/DV.jpeg",
  "Leia Organa": "./images/Leia.jpeg",
  "Owen Lars": "./images/OwenL.jpeg",
  "Beru Whitesun lars": "./images/BeruL.jpeg",
  "R5-D4": "./images/R5D4.jpeg",
  "Biggs Darklighter": "./images/BiggsD.jpeg",
  "Obi-wan Kenobi": "./images/Obiwan.jpeg",
  "Alderaan": "./images/Alderaan.jpeg",
  "Yavin IV": "./images/Yavin.jpeg",
  "Hoth": "./images/Hoth.jpeg",
  "Dagobah": "./images/Dagobah.jpeg",
  "Bespin": "./images/Bespin.jpeg",
  "Endor": "./images/Endor.jpeg",
  "Naboo": "./images/Naboo.jpeg",
  "Coruscant": "./images/Coruscant.jpeg",
  "Kamino": "./images/Kamino.jpeg",
  "Geonosis": "./images/Geonosis.jpeg",
  "Sand Crawler": "./images/SandC.jpeg",
  "T-16 skyhopper": "./images/T16.jpeg",
  "X-34 landspeeder": "./images/X34.jpeg",
  "TIE/LN starfighter": "./images/Starfighter.jpeg",
  "Snowspeeder": "./images/Snowspeeder.jpeg",
  "TIE bomber": "./images/TIEbomber.jpeg",
  "AT-AT": "./images/ATAT.jpeg",
  "AT-ST": "./images/ATST.jpeg",
  "Storm IV Twin-Pod cloud car": "./images/StormIV.jpeg",
  "Sail barge": "./images/SailBarge.jpeg",
}

module.exports = contentImages;
